// <auto-generated />
using System;
using BPT.Test.DIBL.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BPT.Test.DIBL.API.Migrations
{
    [DbContext(typeof(PagaTodoDbContext))]
    partial class PagaTodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BPT.Test.DIBL.API.Models.Asignacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Asignaciones");
                });

            modelBuilder.Entity("BPT.Test.DIBL.API.Models.AsignacionesEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdAsignacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstudiante")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAsignacion");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("AsignacionesEstudiante");
                });

            modelBuilder.Entity("BPT.Test.DIBL.API.Models.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("BPT.Test.DIBL.API.Models.AsignacionesEstudiante", b =>
                {
                    b.HasOne("BPT.Test.DIBL.API.Models.Asignacione", "IdAsignacionNavigation")
                        .WithMany("AsignacionesEstudiantes")
                        .HasForeignKey("IdAsignacion")
                        .HasConstraintName("FK_AsignacionesEstudiante_Asignaciones")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BPT.Test.DIBL.API.Models.Estudiante", "IdEstudianteNavigation")
                        .WithMany("AsignacionesEstudiantes")
                        .HasForeignKey("IdEstudiante")
                        .HasConstraintName("FK_AsignacionesEstudiante_Estudiantes")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdAsignacionNavigation");

                    b.Navigation("IdEstudianteNavigation");
                });

            modelBuilder.Entity("BPT.Test.DIBL.API.Models.Asignacione", b =>
                {
                    b.Navigation("AsignacionesEstudiantes");
                });

            modelBuilder.Entity("BPT.Test.DIBL.API.Models.Estudiante", b =>
                {
                    b.Navigation("AsignacionesEstudiantes");
                });
#pragma warning restore 612, 618
        }
    }
}
